[package]
name = "surreal-poem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poem = { version = "1.3.48", features = [ "static-files" ] }
surrealdb = "1.0.0-beta.8"
patch = "0.6.0"